export default {
  TICKS_PER_TURN: 16,
  COLLISION_DETECTION_SUBTICKS: 8,
  COLLISION_CHECK_RADIUS: 32,

  UNIT_WIDTH: 12,
  UNIT_HEIGHT: 24,
  UNIT_HITBOX_ALTITUDE: 1.4,
  UNIT_RANGE_MARGIN: 6,

  TILE_SIZE: 16,
  UNIT_ROTATION_SPEED: 0.26179939, // 15 degrees
  UNIT_ROTATION_MAX_THRESHOLD: 0.52359878, // 30 degrees
  RUN_ROTATION_SPEED: 0.22252948, // 15 degrees * 0.85 = 12.75 degrees (85% of base)

  MAX_RANKED_GAME_TURNS: 60,
  MIN_CUSTOM_GAME_MAX_TURNS: 10,
  MAX_CUSTOM_GAME_MAX_TURNS: 99,
  MAX_INACTIVE_TURNS: 2,
  TURN_LIMIT_TIME_MARGIN_SECONDS: 10,
  CAPTURE_OBJECTIVE_THRESHOLD: 8,

  ROUT_THRESHOLD_TURNS: 3,

  ENFILADE_FIRE_ORG_DAMAGE_BONUS: 0.25,
  ENFILADE_FIRE_DAMAGE_BONUS: 0.5,
  REAR_FIRE_ORG_DAMAGE_BONUS: 0.75,
  ROUTING_MELEE_DAMAGE_RECEIVED_MODIFIER: 0.25,

  MIN_MOVEMENT_MODIFIER: -0.5,
  MIN_ROUTING_MOVEMENT_MODIFIER: -0.25,

  DEFAULT_MAP_WIDTH: 1504,
  DEFAULT_MAP_HEIGHT: 1312,
  DEFAULT_DEPLOYMENT_ZONE_WIDTH: 832,
  DEFAULT_DEPLOYMENT_ZONE_HEIGHT: 192,
  DEFAULT_DEPLOYMENT_ZONE_SEPARATION: 512,

  MAX_PLAYERS: 10,
  MIN_FOLLOW_ALLY_DISTANCE_SQUARED: 256, // 16 ** 2
  ALLY_HARD_COLLISION_THRESHOLD: 100,

  FOLLOW_ROTATION_THRESHOLD: 0.7853981633974483, // PI / 4
  CAN_LEAVE_MAP_MIN_ORG: 80,
  CAN_LEAVE_MAP_MIN_HP_PROPORTION: 0.75,

  ORG_SPEED_MODIFIER: -0.15,

  ATTACK_COOLDOWN: 2,

  RUN_STAMINA_TURN_COST: 84,
  WALK_STAMINA_TURN_COST: 8,
  MELEE_STAMINA_TURN_COST: 108,
  RANGED_STAMINA_TURN_COST: 48,
  CHARGE_STAMINA_PERCENTAGE_COST: 0.08,

  STAMINA_RANGE_1_REGAIN_RATE: 0.08,
  STAMINA_RANGE_2_REGAIN_RATE: 0.06,
  STAMINA_RANGE_3_REGAIN_RATE: 0.045,
  STAMINA_RANGE_4_REGAIN_RATE: 0.03,
  STAMINA_RANGE_5_REGAIN_RATE: 0.015,

  MAX_ORG_DEBUFF_MIN_HP_PROPORTION: 0.25,
  MAX_ORG_DEBUFF_HP: 0.5,
  MAX_ORG_DEBUFF_STAMINA: 0.3,
  MAX_ORG_DEBUFF_STAMINA_HIGH_PROPORTION: 0.8,
  MAX_ORG_DEBUFF_STAMINA_LOW_PROPORTION: 0.2,

  STAMINA_UPPER_MODIFIER_LIMIT: 0.8,
  STAMINA_LOWER_MODIFIER_LIMIT: 0.2,

  ALLY_OVERLAP_MAX_SPEED_PENALTY: -0.5,
  ALLY_OVERLAP_MAX_ORG_DAMAGE_RECEIVED: 0.3,
  ALLY_OVERLAP_MAX_MELEE_ATTACK_PENALTY: -0.5,
  ALLY_OVERLAP_UPPER_MODIFIER_LIMIT: 0.6,
  ALLY_OVERLAP_LOWER_MODIFIER_LIMIT: 0,
  ALLY_OVERLAP_STOP_CHARGE: 0.5,

  STAMINA_CHARGE_RESISTANCE_MODIFIER: -0.4,

  MAX_STAMINA_RUNNING_MOVEMENT_PENALTY: -0.5,
  MAX_STAMINA_RANGED_ATTACK_PENALTY: -0.4,

  MAX_STAMINA_MELEE_ATTACK_PENALTY: -0.5,
  MAX_STAMINA_MELEE_DEFENSE_PENALTY: -0.25,

  MAX_HP_RANGED_ATTACK_PENALTY: -0.5,
  MAX_ORG_RANGED_ATTACK_PENALTY: -0.5,

  MAX_HP_MELEE_ATTACK_BONUS: 0.25,
  MAX_HP_MELEE_ATTACK_PENALTY: 0.75,

  MAX_ORG_MELEE_ATTACK_BONUS: 0.25,
  MAX_ORG_MELEE_ATTACK_PENALTY: 0.25,

  ORG_REGAIN_RATE: 0.12,
  RECOVER_FROM_ROUTING_THRESHOLD: 0.3,
  ORG_UPPER_MODIFIER_LIMIT: 0.8,
  ORG_LOWER_MODIFIER_LIMIT: 0.5,

  NEARBY_UNITS_DISTANCE: 64,
  NEARBY_UNITS_POSITIVE_ORG_BONUS_CAP: 75,
  NEARBY_UNITS_NEGATIVE_ORG_BONUS_CAP: -75,

  /**
   * This org damage modifier is applied positively or negatively if the unit
   * has reached one of the nearby units org bonus caps.
   */
  NEARBY_UNITS_ORG_DAMAGE_MODIFIER_CAP: 0.1,

  NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_CAP: 0.2,
  NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_CAP: 0.2,

  /**
   * Routing units will receive the org bonus by nearby units multiplied by this value.
   */
  ROUTING_UNIT_NEARBY_UNITS_ORG_BONUS: 1.5,

  STARTED_ROUTING_ORG_RADIUS_MODIFIER: -4.0,
  MAX_ALLY_OVERLAP_ORG_RADIUS_MODIFIER: -0.6,

  SAFE_ORG_RECOVERY_MODIFIER: 0.5,
  SAFE_DISTANCE: 222,

  DISTANT_THREAT_ORG_RECOVERY_MODIFIER: 0.25,
  DISTANT_THREAT_DISTANCE: 108,
  ROUTING_ORG_RECOVERY_MODIFIER: -0.5,

  MAX_ORG_RECOVERY_BY_HP_MODIFIER: -0.9,
  MIN_HP_PROPORTION_FOR_SAFE_RECOVERY: 0.6,

  ORG_VICTORY_POINTS_THRESHOLD: 35,
  NO_VICTORY_POINTS_ORG_MODIFIER: -10, // -1000%
  ORG_VPS_MODIFIER_MULTIPLIER: 1.5,
  MIN_EFFECTIVE_VPS: 5,

  OBJECTIVE_RADIUS: 64, // 4 tiles
  SHOT_TRAJECTORY_TARGET_ALTITUDE: 0.9,

  OFFER_DRAW_COOLDOWN: 10,
  MAX_ENTITY_NAME_LENGTH: 32,
  CHARGE_BACKLASH_BASE: 1.0,
  CHARGE_BACKLASH_DEFENDER_CHARGE_BONUS_MULTIPLIER: 1.25,

  HAS_TAKEN_FIRE_SPEED_MODIFIER: -0.1,
  HAS_TAKEN_FIRE_CHARGE_RESISTANCE_MODIFIER: -0.3,
  HAS_TAKEN_FIRE_CHARGE_PENETRATION_MODIFIER: -0.2,
  BEEN_IN_MELEE_CHARGE_RESISTANCE_MODIFIER: -0.15,

  EFFECT_BEEN_IN_MELEE_TICKS: 12,
  EFFECT_FULL_STOP_ON_ROTATE_180_TICKS: 6,
  EFFECT_HAS_RAN_TICKS: 9,
  EFFECT_STARTED_ROUTING_TICKS: 16,
  EFFECT_HAS_TAKEN_FIRE_TICKS: 6,

  FLANK_MELEE_ORG_DAMAGE_MODIFIER: 1,
  REAR_MELEE_ORG_DAMAGE_MODIFIER: 1,

  FLANK_CHARGE_PENETRATION_MODIFIER: 1,
  REAR_CHARGE_PENETRATION_MODIFIER: 1,

  DEPLOYMENT_TURN_ADDITIONAL_SECONDS: 30,
  HEAD_ON_COLLISION_COSINE_THRESHOLD_SQUARED: 0.015625, // 0.125 * 0.125

  HEIGHT_CHANGE_STAMINA_COST: 0.02, // 2% stamina cost for height changes
  HEIGHT_CHANGE_TICKS: 12,
  HEIGHT_CHANGE_RUNNING_STAMINA_COST: 0.04, // 4% stamina cost for height changes when running
};
